universe = vanilla

executable = @exe@

log = @log@
output = @out@
error = @err@

#transfer_input_files = condor_script.sh
should_transfer_files = YES

when_to_transfer_output = ON_EXIT_OR_EVICT

getenv = True

# Send the job to Held state on failure. 
#on_exit_hold = (ExitBySignal == True) || (ExitCode != 0)

#max_retries = 2

# In MB
request_memory = 6000

# In seconds
+MaxRuntime = 172800

queue
