cmsRun MyModules/Test/python/reco_test_RAW2DIGI_L1Reco_RECO_RECOSIM_withTICL_mod.py \
    sourceFile=sourceFiles/SingleElectron_PT2to200_Phase2HLTTDRWinter20DIGI-PU200_110X_mcRun4_realistic_v3_ext2-v2_GEN-SIM-DIGI-RAW/SingleElectron_PT2to200_Phase2HLTTDRWinter20DIGI-PU200_110X_mcRun4_realistic_v3_ext2-v2_GEN-SIM-DIGI-RAW.txt \
    outputFile=output_modRECO.root \
    maxEvents=5 \
    dropList=\
recoPFClusters_particleFlowClusterHGCal_*_*,\
PixelDigiSimLinkedmDetSetVector_simSiPixelDigis_Tracker_*,\
DetIdHGCSampleHGCDataFramesSorted_simHGCalUnsuppressedDigis_EE_*,\
PixelDigiSimLinkedmDetSetVector_simSiPixelDigis_Pixel_*,\
Phase2TrackerDigiedmDetSetVectorPhase2TrackerDigiPhase2TrackerDigiedmrefhelperFindForDetSetVectoredmRefTTClusteredmNewDetSetVector_TTClustersFromPhase2TrackerDigis_ClusterInclusive_*,\
recoGsfPFRecTracks_pfTrackElec_Secondary_*,\
PixelDigiedmDetSetVector_simSiPixelDigis_Pixel_*,\
recoCaloClusters_particleFlowSuperClusterHGCal__*\
    keepList=\
*_generator_*_*,\
*_genParticles_*_*,\
*_addPileupInfo_*_*,\
*_fixedGridRhoFastjetAll_*_*,\
*_g4SimHits_*_*,\
*_HGCalRecHit_*_*,\
*_HGCalRecHit_*_*,\
*_mix_MergedCaloTruth_*,\
*_*FromMultiCl_*_*,\
\
*_HGCalUncalibRecHit_*_*,\
*_MeasurementTrackerEvent_*_*,\
*_TriggerResults_*_*,\
*_ak4CaloJetsForTrk_*_*,\
*_caloTowerForTrk_*_*,\
*_detachedQuadStep_*_*,\
*_detachedQuadStepClusters_*_*,\
*_detachedQuadStepHitDoublets_*_*,\
*_detachedQuadStepHitQuadruplets_*_*,\
*_detachedQuadStepSeedLayers_*_*,\
*_detachedQuadStepSeeds_*_*,\
*_detachedQuadStepSelector_*_*,\
*_detachedQuadStepTrackCandidates_*_*,\
*_detachedQuadStepTrackingRegions_*_*,\
*_detachedQuadStepTracks_*_*,\
*_ecalDrivenElectronSeedsFromTICL_*_*,\
*_ecalDrivenGsfElectronCoresFromTICL_*_*,\
*_ecalDrivenGsfElectronsFromTICL_*_*,\
*_electronCkfTrackCandidatesFromTICL_*_*,\
*_electronGsfTracksFromTICL_*_*,\
*_electronMergedSeedsFromTICL_*_*,\
*_filteredLayerClusters_*_*,\
*_filteredLayerClustersMIP_*_*,\
*_filteredLayerClustersTrk_*_*,\
*_firstStepPrimaryVertices_*_*,\
*_firstStepPrimaryVerticesUnsorted_*_*,\
*_hgcalLayerClusters_*_*,\
*_hgcalMultiClusters_*_*,\
*_highPtTripletStepClusters_*_*,\
*_highPtTripletStepHitDoublets_*_*,\
*_highPtTripletStepHitTriplets_*_*,\
*_highPtTripletStepSeedClusterMask_*_*,\
*_highPtTripletStepSeedLayers_*_*,\
*_highPtTripletStepSeeds_*_*,\
*_highPtTripletStepSelector_*_*,\
*_highPtTripletStepTrackCandidates_*_*,\
*_highPtTripletStepTrackingRegions_*_*,\
*_highPtTripletStepTracks_*_*,\
*_initialStepHitDoublets_*_*,\
*_initialStepHitQuadruplets_*_*,\
*_initialStepSeedClusterMask_*_*,\
*_initialStepSeedLayers_*_*,\
*_initialStepSeeds_*_*,\
*_initialStepSelector_*_*,\
*_initialStepTrackCandidates_*_*,\
*_initialStepTrackRefsForJets_*_*,\
*_initialStepTrackingRegions_*_*,\
*_initialStepTracks_*_*,\
*_lowPtQuadStepClusters_*_*,\
*_lowPtQuadStepHitDoublets_*_*,\
*_lowPtQuadStepHitQuadruplets_*_*,\
*_lowPtQuadStepSeedLayers_*_*,\
*_lowPtQuadStepSeeds_*_*,\
*_lowPtQuadStepSelector_*_*,\
*_lowPtQuadStepTrackCandidates_*_*,\
*_lowPtQuadStepTrackingRegions_*_*,\
*_lowPtQuadStepTracks_*_*,\
*_lowPtTripletStepClusters_*_*,\
*_lowPtTripletStepHitDoublets_*_*,\
*_lowPtTripletStepHitTriplets_*_*,\
*_lowPtTripletStepSeedLayers_*_*,\
*_lowPtTripletStepSeeds_*_*,\
*_lowPtTripletStepSelector_*_*,\
*_lowPtTripletStepTrackCandidates_*_*,\
*_lowPtTripletStepTrackingRegions_*_*,\
*_lowPtTripletStepTracks_*_*,\
*_multiClustersFromTrackstersEM_*_*,\
*_multiClustersFromTrackstersHAD_*_*,\
*_multiClustersFromTrackstersMIP_*_*,\
*_multiClustersFromTrackstersTrk_*_*,\
*_newCombinedSeeds_*_*,\
*_particleFlowClusterHGCalFromMultiCl_*_*,\
*_particleFlowClusterHGCalFromTICL_*_*,\
*_particleFlowRecHitHGC_*_*,\
*_particleFlowSuperClusterHGCalFromTICL_*_*,\
*_pfTICLProducer_*_*,\
*_pixelPairStepClusters_*_*,\
*_pixelPairStepHitDoublets_*_*,\
*_pixelPairStepSeedClusterMask_*_*,\
*_pixelPairStepSeedLayers_*_*,\
*_pixelPairStepSeeds_*_*,\
*_pixelPairStepSelector_*_*,\
*_pixelPairStepTrackCandidates_*_*,\
*_pixelPairStepTrackingRegions_*_*,\
*_pixelPairStepTracks_*_*,\
*_siPixelClusterShapeCache_*_*,\
*_siPixelRecHits_*_*,\
*_ticlCandidateFromTrackstersProducer_*_*,\
*_ticlLayerTileProducer_*_*,\
*_ticlSeedingGlobal_*_*,\
*_ticlSeedingTrk_*_*,\
*_trackerClusterCheck_*_*,\
*_trackstersEM_*_*,\
*_trackstersHAD_*_*,\
*_trackstersMIP_*_*,\
*_trackstersTrk_*_*,\
*_tripletElectronHitDoublets_*_*,\
*_tripletElectronHitTriplets_*_*,\
*_tripletElectronSeedLayers_*_*,\
*_tripletElectronSeeds_*_*,\
*_tripletElectronTrackingRegions_*_*
